//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCC.ActiveDirectoryGroupUsers {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GroupUsers", Namespace="http://schemas.datacontract.org/2004/07/ActiveDirectoryGroupUsers.Modelos")]
    [System.SerializableAttribute()]
    public partial class GroupUsers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GCC.ActiveDirectoryGroupUsers.Users[] UsersListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupNameDescription {
            get {
                return this.GroupNameDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameDescriptionField, value) != true)) {
                    this.GroupNameDescriptionField = value;
                    this.RaisePropertyChanged("GroupNameDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GCC.ActiveDirectoryGroupUsers.Users[] UsersList {
            get {
                return this.UsersListField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersListField, value) != true)) {
                    this.UsersListField = value;
                    this.RaisePropertyChanged("UsersList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/ActiveDirectoryGroupUsers.Modelos")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CentroCustoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EnderecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutroContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] PhotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeOrganicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnidadeOrganicaDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XnucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XnucApelidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XnucNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CentroCusto {
            get {
                return this.CentroCustoField;
            }
            set {
                if ((object.ReferenceEquals(this.CentroCustoField, value) != true)) {
                    this.CentroCustoField = value;
                    this.RaisePropertyChanged("CentroCusto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contacto {
            get {
                return this.ContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactoField, value) != true)) {
                    this.ContactoField = value;
                    this.RaisePropertyChanged("Contacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Endereco {
            get {
                return this.EnderecoField;
            }
            set {
                if ((object.ReferenceEquals(this.EnderecoField, value) != true)) {
                    this.EnderecoField = value;
                    this.RaisePropertyChanged("Endereco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OutroContacto {
            get {
                return this.OutroContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.OutroContactoField, value) != true)) {
                    this.OutroContactoField = value;
                    this.RaisePropertyChanged("OutroContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Photo {
            get {
                return this.PhotoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhotoField, value) != true)) {
                    this.PhotoField = value;
                    this.RaisePropertyChanged("Photo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadeOrganica {
            get {
                return this.UnidadeOrganicaField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeOrganicaField, value) != true)) {
                    this.UnidadeOrganicaField = value;
                    this.RaisePropertyChanged("UnidadeOrganica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadeOrganicaDescricao {
            get {
                return this.UnidadeOrganicaDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadeOrganicaDescricaoField, value) != true)) {
                    this.UnidadeOrganicaDescricaoField = value;
                    this.RaisePropertyChanged("UnidadeOrganicaDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Xnuc {
            get {
                return this.XnucField;
            }
            set {
                if ((object.ReferenceEquals(this.XnucField, value) != true)) {
                    this.XnucField = value;
                    this.RaisePropertyChanged("Xnuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XnucApelido {
            get {
                return this.XnucApelidoField;
            }
            set {
                if ((object.ReferenceEquals(this.XnucApelidoField, value) != true)) {
                    this.XnucApelidoField = value;
                    this.RaisePropertyChanged("XnucApelido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XnucName {
            get {
                return this.XnucNameField;
            }
            set {
                if ((object.ReferenceEquals(this.XnucNameField, value) != true)) {
                    this.XnucNameField = value;
                    this.RaisePropertyChanged("XnucName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorMessages", Namespace="http://schemas.datacontract.org/2004/07/ActiveDirectoryGroupUsers.Modelos")]
    [System.SerializableAttribute()]
    public partial class ErrorMessages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DetalheMensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessagemField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalheMensagem {
            get {
                return this.DetalheMensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.DetalheMensagemField, value) != true)) {
                    this.DetalheMensagemField = value;
                    this.RaisePropertyChanged("DetalheMensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Messagem {
            get {
                return this.MessagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagemField, value) != true)) {
                    this.MessagemField = value;
                    this.RaisePropertyChanged("Messagem");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ActiveDirectoryGroupUsers.IUsersServiceAD")]
    public interface IUsersServiceAD {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersServiceAD/GetUsersListAD", ReplyAction="http://tempuri.org/IUsersServiceAD/GetUsersListADResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GCC.ActiveDirectoryGroupUsers.ErrorMessages), Action="http://tempuri.org/IUsersServiceAD/GetUsersListADErrorMessagesFault", Name="ErrorMessages", Namespace="http://schemas.datacontract.org/2004/07/ActiveDirectoryGroupUsers.Modelos")]
        GCC.ActiveDirectoryGroupUsers.GroupUsers[] GetUsersListAD(string inGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersServiceAD/GetUsersListAD", ReplyAction="http://tempuri.org/IUsersServiceAD/GetUsersListADResponse")]
        System.Threading.Tasks.Task<GCC.ActiveDirectoryGroupUsers.GroupUsers[]> GetUsersListADAsync(string inGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersServiceAD/GetUsersByGroupName", ReplyAction="http://tempuri.org/IUsersServiceAD/GetUsersByGroupNameResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GCC.ActiveDirectoryGroupUsers.ErrorMessages), Action="http://tempuri.org/IUsersServiceAD/GetUsersByGroupNameErrorMessagesFault", Name="ErrorMessages", Namespace="http://schemas.datacontract.org/2004/07/ActiveDirectoryGroupUsers.Modelos")]
        GCC.ActiveDirectoryGroupUsers.GroupUsers GetUsersByGroupName(string inGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersServiceAD/GetUsersByGroupName", ReplyAction="http://tempuri.org/IUsersServiceAD/GetUsersByGroupNameResponse")]
        System.Threading.Tasks.Task<GCC.ActiveDirectoryGroupUsers.GroupUsers> GetUsersByGroupNameAsync(string inGroup);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersServiceAD/GetUsersGroupMembers", ReplyAction="http://tempuri.org/IUsersServiceAD/GetUsersGroupMembersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GCC.ActiveDirectoryGroupUsers.ErrorMessages), Action="http://tempuri.org/IUsersServiceAD/GetUsersGroupMembersErrorMessagesFault", Name="ErrorMessages", Namespace="http://schemas.datacontract.org/2004/07/ActiveDirectoryGroupUsers.Modelos")]
        string[] GetUsersGroupMembers(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersServiceAD/GetUsersGroupMembers", ReplyAction="http://tempuri.org/IUsersServiceAD/GetUsersGroupMembersResponse")]
        System.Threading.Tasks.Task<string[]> GetUsersGroupMembersAsync(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersServiceAD/GetUserByXnuc", ReplyAction="http://tempuri.org/IUsersServiceAD/GetUserByXnucResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GCC.ActiveDirectoryGroupUsers.ErrorMessages), Action="http://tempuri.org/IUsersServiceAD/GetUserByXnucErrorMessagesFault", Name="ErrorMessages", Namespace="http://schemas.datacontract.org/2004/07/ActiveDirectoryGroupUsers.Modelos")]
        GCC.ActiveDirectoryGroupUsers.Users GetUserByXnuc(string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUsersServiceAD/GetUserByXnuc", ReplyAction="http://tempuri.org/IUsersServiceAD/GetUserByXnucResponse")]
        System.Threading.Tasks.Task<GCC.ActiveDirectoryGroupUsers.Users> GetUserByXnucAsync(string userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUsersServiceADChannel : GCC.ActiveDirectoryGroupUsers.IUsersServiceAD, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersServiceADClient : System.ServiceModel.ClientBase<GCC.ActiveDirectoryGroupUsers.IUsersServiceAD>, GCC.ActiveDirectoryGroupUsers.IUsersServiceAD {
        
        public UsersServiceADClient() {
        }
        
        public UsersServiceADClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersServiceADClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceADClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersServiceADClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GCC.ActiveDirectoryGroupUsers.GroupUsers[] GetUsersListAD(string inGroup) {
            return base.Channel.GetUsersListAD(inGroup);
        }
        
        public System.Threading.Tasks.Task<GCC.ActiveDirectoryGroupUsers.GroupUsers[]> GetUsersListADAsync(string inGroup) {
            return base.Channel.GetUsersListADAsync(inGroup);
        }
        
        public GCC.ActiveDirectoryGroupUsers.GroupUsers GetUsersByGroupName(string inGroup) {
            return base.Channel.GetUsersByGroupName(inGroup);
        }
        
        public System.Threading.Tasks.Task<GCC.ActiveDirectoryGroupUsers.GroupUsers> GetUsersByGroupNameAsync(string inGroup) {
            return base.Channel.GetUsersByGroupNameAsync(inGroup);
        }
        
        public string[] GetUsersGroupMembers(string userID) {
            return base.Channel.GetUsersGroupMembers(userID);
        }
        
        public System.Threading.Tasks.Task<string[]> GetUsersGroupMembersAsync(string userID) {
            return base.Channel.GetUsersGroupMembersAsync(userID);
        }
        
        public GCC.ActiveDirectoryGroupUsers.Users GetUserByXnuc(string userID) {
            return base.Channel.GetUserByXnuc(userID);
        }
        
        public System.Threading.Tasks.Task<GCC.ActiveDirectoryGroupUsers.Users> GetUserByXnucAsync(string userID) {
            return base.Channel.GetUserByXnucAsync(userID);
        }
    }
}
