//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCC.CatalogoProduto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://schemas.datacontract.org/2004/07/WSCatalogoProdutos.BLL.Models")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<GCC.CatalogoProduto.Produto> ChildrenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isLastField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<GCC.CatalogoProduto.Produto> Children {
            get {
                return this.ChildrenField;
            }
            set {
                if ((object.ReferenceEquals(this.ChildrenField, value) != true)) {
                    this.ChildrenField = value;
                    this.RaisePropertyChanged("Children");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentProductID {
            get {
                return this.ParentProductIDField;
            }
            set {
                if ((this.ParentProductIDField.Equals(value) != true)) {
                    this.ParentProductIDField = value;
                    this.RaisePropertyChanged("ParentProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCod {
            get {
                return this.ProductCodField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodField, value) != true)) {
                    this.ProductCodField = value;
                    this.RaisePropertyChanged("ProductCod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductLevel {
            get {
                return this.ProductLevelField;
            }
            set {
                if ((this.ProductLevelField.Equals(value) != true)) {
                    this.ProductLevelField = value;
                    this.RaisePropertyChanged("ProductLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isLast {
            get {
                return this.isLastField;
            }
            set {
                if ((this.isLastField.Equals(value) != true)) {
                    this.isLastField = value;
                    this.RaisePropertyChanged("isLast");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/WSCatalogoProdutos.BLL.Models")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ParentProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductCodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ProductLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> isLastField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ParentProductID {
            get {
                return this.ParentProductIDField;
            }
            set {
                if ((this.ParentProductIDField.Equals(value) != true)) {
                    this.ParentProductIDField = value;
                    this.RaisePropertyChanged("ParentProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCod {
            get {
                return this.ProductCodField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductCodField, value) != true)) {
                    this.ProductCodField = value;
                    this.RaisePropertyChanged("ProductCod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProductLevel {
            get {
                return this.ProductLevelField;
            }
            set {
                if ((this.ProductLevelField.Equals(value) != true)) {
                    this.ProductLevelField = value;
                    this.RaisePropertyChanged("ProductLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> isLast {
            get {
                return this.isLastField;
            }
            set {
                if ((this.isLastField.Equals(value) != true)) {
                    this.isLastField = value;
                    this.RaisePropertyChanged("isLast");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProdutoFile", Namespace="http://schemas.datacontract.org/2004/07/WSCatalogoProdutos.BLL.Models")]
    [System.SerializableAttribute()]
    public partial class ProdutoFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FileIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileLinkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileID {
            get {
                return this.FileIDField;
            }
            set {
                if ((this.FileIDField.Equals(value) != true)) {
                    this.FileIDField = value;
                    this.RaisePropertyChanged("FileID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileLink {
            get {
                return this.FileLinkField;
            }
            set {
                if ((object.ReferenceEquals(this.FileLinkField, value) != true)) {
                    this.FileLinkField = value;
                    this.RaisePropertyChanged("FileLink");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((this.ProductIDField.Equals(value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FichaProduto", Namespace="http://schemas.datacontract.org/2004/07/WSCatalogoProdutos.BLL.Models")]
    [System.SerializableAttribute()]
    public partial class FichaProduto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> FichaDadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> FichaDados {
            get {
                return this.FichaDadosField;
            }
            set {
                if ((object.ReferenceEquals(this.FichaDadosField, value) != true)) {
                    this.FichaDadosField = value;
                    this.RaisePropertyChanged("FichaDados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CatalogoProduto.IWSCatalogoProdutos")]
    public interface IWSCatalogoProdutos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProdutobyID", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProdutobyIDResponse")]
        GCC.CatalogoProduto.Produto GetProdutobyID(int ProdutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProdutobyID", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProdutobyIDResponse")]
        System.Threading.Tasks.Task<GCC.CatalogoProduto.Produto> GetProdutobyIDAsync(int ProdutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProdutobyCod", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProdutobyCodResponse")]
        GCC.CatalogoProduto.Produto GetProdutobyCod(string ProdutoCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProdutobyCod", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProdutobyCodResponse")]
        System.Threading.Tasks.Task<GCC.CatalogoProduto.Produto> GetProdutobyCodAsync(string ProdutoCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProductList", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProductListResponse")]
        System.Collections.Generic.List<GCC.CatalogoProduto.Produto> GetProductList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProductList", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProductListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Produto>> GetProductListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetAllProductList", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetAllProductListResponse")]
        System.Collections.Generic.List<GCC.CatalogoProduto.Product> GetAllProductList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetAllProductList", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetAllProductListResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Product>> GetAllProductListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyID", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyIDResponse")]
        System.Collections.Generic.List<GCC.CatalogoProduto.Produto> GetProductListbyID(int ProdutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyID", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyIDResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Produto>> GetProductListbyIDAsync(int ProdutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyCod", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyCodResponse")]
        System.Collections.Generic.List<GCC.CatalogoProduto.Produto> GetProductListbyCod(string ProdutoCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyCod", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyCodResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Produto>> GetProductListbyCodAsync(string ProdutoCod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyLevel", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyLevelResponse")]
        System.Collections.Generic.List<GCC.CatalogoProduto.Produto> GetProductListbyLevel(int level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyLevel", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetProductListbyLevelResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Produto>> GetProductListbyLevelAsync(int level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetFichaProdutoFiles", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetFichaProdutoFilesResponse")]
        System.Collections.Generic.List<GCC.CatalogoProduto.ProdutoFile> GetFichaProdutoFiles(int ProdutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetFichaProdutoFiles", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetFichaProdutoFilesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.ProdutoFile>> GetFichaProdutoFilesAsync(int ProdutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetFichaProduto", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetFichaProdutoResponse")]
        GCC.CatalogoProduto.FichaProduto GetFichaProduto(int ProdutoID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWSCatalogoProdutos/GetFichaProduto", ReplyAction="http://tempuri.org/IWSCatalogoProdutos/GetFichaProdutoResponse")]
        System.Threading.Tasks.Task<GCC.CatalogoProduto.FichaProduto> GetFichaProdutoAsync(int ProdutoID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWSCatalogoProdutosChannel : GCC.CatalogoProduto.IWSCatalogoProdutos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCatalogoProdutosClient : System.ServiceModel.ClientBase<GCC.CatalogoProduto.IWSCatalogoProdutos>, GCC.CatalogoProduto.IWSCatalogoProdutos {
        
        public WSCatalogoProdutosClient() {
        }
        
        public WSCatalogoProdutosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCatalogoProdutosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCatalogoProdutosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCatalogoProdutosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GCC.CatalogoProduto.Produto GetProdutobyID(int ProdutoID) {
            return base.Channel.GetProdutobyID(ProdutoID);
        }
        
        public System.Threading.Tasks.Task<GCC.CatalogoProduto.Produto> GetProdutobyIDAsync(int ProdutoID) {
            return base.Channel.GetProdutobyIDAsync(ProdutoID);
        }
        
        public GCC.CatalogoProduto.Produto GetProdutobyCod(string ProdutoCod) {
            return base.Channel.GetProdutobyCod(ProdutoCod);
        }
        
        public System.Threading.Tasks.Task<GCC.CatalogoProduto.Produto> GetProdutobyCodAsync(string ProdutoCod) {
            return base.Channel.GetProdutobyCodAsync(ProdutoCod);
        }
        
        public System.Collections.Generic.List<GCC.CatalogoProduto.Produto> GetProductList() {
            return base.Channel.GetProductList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Produto>> GetProductListAsync() {
            return base.Channel.GetProductListAsync();
        }
        
        public System.Collections.Generic.List<GCC.CatalogoProduto.Product> GetAllProductList() {
            return base.Channel.GetAllProductList();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Product>> GetAllProductListAsync() {
            return base.Channel.GetAllProductListAsync();
        }
        
        public System.Collections.Generic.List<GCC.CatalogoProduto.Produto> GetProductListbyID(int ProdutoID) {
            return base.Channel.GetProductListbyID(ProdutoID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Produto>> GetProductListbyIDAsync(int ProdutoID) {
            return base.Channel.GetProductListbyIDAsync(ProdutoID);
        }
        
        public System.Collections.Generic.List<GCC.CatalogoProduto.Produto> GetProductListbyCod(string ProdutoCod) {
            return base.Channel.GetProductListbyCod(ProdutoCod);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Produto>> GetProductListbyCodAsync(string ProdutoCod) {
            return base.Channel.GetProductListbyCodAsync(ProdutoCod);
        }
        
        public System.Collections.Generic.List<GCC.CatalogoProduto.Produto> GetProductListbyLevel(int level) {
            return base.Channel.GetProductListbyLevel(level);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.Produto>> GetProductListbyLevelAsync(int level) {
            return base.Channel.GetProductListbyLevelAsync(level);
        }
        
        public System.Collections.Generic.List<GCC.CatalogoProduto.ProdutoFile> GetFichaProdutoFiles(int ProdutoID) {
            return base.Channel.GetFichaProdutoFiles(ProdutoID);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<GCC.CatalogoProduto.ProdutoFile>> GetFichaProdutoFilesAsync(int ProdutoID) {
            return base.Channel.GetFichaProdutoFilesAsync(ProdutoID);
        }
        
        public GCC.CatalogoProduto.FichaProduto GetFichaProduto(int ProdutoID) {
            return base.Channel.GetFichaProduto(ProdutoID);
        }
        
        public System.Threading.Tasks.Task<GCC.CatalogoProduto.FichaProduto> GetFichaProdutoAsync(int ProdutoID) {
            return base.Channel.GetFichaProdutoAsync(ProdutoID);
        }
    }
}
