//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GCC.Permissoes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Permissoes.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name User_ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsValUsrPerfil", ReplyAction="*")]
        GCC.Permissoes.wsValUsrPerfilResponse wsValUsrPerfil(GCC.Permissoes.wsValUsrPerfilRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsValUsrPerfil", ReplyAction="*")]
        System.Threading.Tasks.Task<GCC.Permissoes.wsValUsrPerfilResponse> wsValUsrPerfilAsync(GCC.Permissoes.wsValUsrPerfilRequest request);
        
        // CODEGEN: Generating message contract since element name wsPerfil from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsValPerfilFuncao", ReplyAction="*")]
        GCC.Permissoes.wsValPerfilFuncaoResponse wsValPerfilFuncao(GCC.Permissoes.wsValPerfilFuncaoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsValPerfilFuncao", ReplyAction="*")]
        System.Threading.Tasks.Task<GCC.Permissoes.wsValPerfilFuncaoResponse> wsValPerfilFuncaoAsync(GCC.Permissoes.wsValPerfilFuncaoRequest request);
        
        // CODEGEN: Generating message contract since element name User_ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsValUsr", ReplyAction="*")]
        GCC.Permissoes.wsValUsrResponse wsValUsr(GCC.Permissoes.wsValUsrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsValUsr", ReplyAction="*")]
        System.Threading.Tasks.Task<GCC.Permissoes.wsValUsrResponse> wsValUsrAsync(GCC.Permissoes.wsValUsrRequest request);
        
        // CODEGEN: Generating message contract since element name User_ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsAccessControl", ReplyAction="*")]
        GCC.Permissoes.wsAccessControlResponse wsAccessControl(GCC.Permissoes.wsAccessControlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsAccessControl", ReplyAction="*")]
        System.Threading.Tasks.Task<GCC.Permissoes.wsAccessControlResponse> wsAccessControlAsync(GCC.Permissoes.wsAccessControlRequest request);
        
        // CODEGEN: Generating message contract since element name User_ID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsAuditoriaWebbank", ReplyAction="*")]
        GCC.Permissoes.wsAuditoriaWebbankResponse wsAuditoriaWebbank(GCC.Permissoes.wsAuditoriaWebbankRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/wsAuditoriaWebbank", ReplyAction="*")]
        System.Threading.Tasks.Task<GCC.Permissoes.wsAuditoriaWebbankResponse> wsAuditoriaWebbankAsync(GCC.Permissoes.wsAuditoriaWebbankRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsValUsrPerfilRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsValUsrPerfil", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsValUsrPerfilRequestBody Body;
        
        public wsValUsrPerfilRequest() {
        }
        
        public wsValUsrPerfilRequest(GCC.Permissoes.wsValUsrPerfilRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wsValUsrPerfilRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Rq_Page;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string User_Perfil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string App;
        
        public wsValUsrPerfilRequestBody() {
        }
        
        public wsValUsrPerfilRequestBody(string User_ID, string Rq_Page, string User_Perfil, string App) {
            this.User_ID = User_ID;
            this.Rq_Page = Rq_Page;
            this.User_Perfil = User_Perfil;
            this.App = App;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsValUsrPerfilResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsValUsrPerfilResponse", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsValUsrPerfilResponseBody Body;
        
        public wsValUsrPerfilResponse() {
        }
        
        public wsValUsrPerfilResponse(GCC.Permissoes.wsValUsrPerfilResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wsValUsrPerfilResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool wsValUsrPerfilResult;
        
        public wsValUsrPerfilResponseBody() {
        }
        
        public wsValUsrPerfilResponseBody(bool wsValUsrPerfilResult) {
            this.wsValUsrPerfilResult = wsValUsrPerfilResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsValPerfilFuncaoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsValPerfilFuncao", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsValPerfilFuncaoRequestBody Body;
        
        public wsValPerfilFuncaoRequest() {
        }
        
        public wsValPerfilFuncaoRequest(GCC.Permissoes.wsValPerfilFuncaoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wsValPerfilFuncaoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string wsPerfil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string wsOperacao;
        
        public wsValPerfilFuncaoRequestBody() {
        }
        
        public wsValPerfilFuncaoRequestBody(string wsPerfil, string wsOperacao) {
            this.wsPerfil = wsPerfil;
            this.wsOperacao = wsOperacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsValPerfilFuncaoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsValPerfilFuncaoResponse", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsValPerfilFuncaoResponseBody Body;
        
        public wsValPerfilFuncaoResponse() {
        }
        
        public wsValPerfilFuncaoResponse(GCC.Permissoes.wsValPerfilFuncaoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wsValPerfilFuncaoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool wsValPerfilFuncaoResult;
        
        public wsValPerfilFuncaoResponseBody() {
        }
        
        public wsValPerfilFuncaoResponseBody(bool wsValPerfilFuncaoResult) {
            this.wsValPerfilFuncaoResult = wsValPerfilFuncaoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsValUsrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsValUsr", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsValUsrRequestBody Body;
        
        public wsValUsrRequest() {
        }
        
        public wsValUsrRequest(GCC.Permissoes.wsValUsrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wsValUsrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Operacao;
        
        public wsValUsrRequestBody() {
        }
        
        public wsValUsrRequestBody(string User_ID, string Operacao) {
            this.User_ID = User_ID;
            this.Operacao = Operacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsValUsrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsValUsrResponse", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsValUsrResponseBody Body;
        
        public wsValUsrResponse() {
        }
        
        public wsValUsrResponse(GCC.Permissoes.wsValUsrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wsValUsrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool wsValUsrResult;
        
        public wsValUsrResponseBody() {
        }
        
        public wsValUsrResponseBody(bool wsValUsrResult) {
            this.wsValUsrResult = wsValUsrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsAccessControlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsAccessControl", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsAccessControlRequestBody Body;
        
        public wsAccessControlRequest() {
        }
        
        public wsAccessControlRequest(GCC.Permissoes.wsAccessControlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wsAccessControlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Operacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Aplicacao;
        
        public wsAccessControlRequestBody() {
        }
        
        public wsAccessControlRequestBody(string User_ID, string Operacao, string Aplicacao) {
            this.User_ID = User_ID;
            this.Operacao = Operacao;
            this.Aplicacao = Aplicacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsAccessControlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsAccessControlResponse", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsAccessControlResponseBody Body;
        
        public wsAccessControlResponse() {
        }
        
        public wsAccessControlResponse(GCC.Permissoes.wsAccessControlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wsAccessControlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool wsAccessControlResult;
        
        public wsAccessControlResponseBody() {
        }
        
        public wsAccessControlResponseBody(bool wsAccessControlResult) {
            this.wsAccessControlResult = wsAccessControlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsAuditoriaWebbankRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsAuditoriaWebbank", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsAuditoriaWebbankRequestBody Body;
        
        public wsAuditoriaWebbankRequest() {
        }
        
        public wsAuditoriaWebbankRequest(GCC.Permissoes.wsAuditoriaWebbankRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class wsAuditoriaWebbankRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string User_ID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Operacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Perfil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Aplicacao;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Pagina;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Descritivo;
        
        public wsAuditoriaWebbankRequestBody() {
        }
        
        public wsAuditoriaWebbankRequestBody(string User_ID, string Operacao, string Perfil, string Aplicacao, string Pagina, string Descritivo) {
            this.User_ID = User_ID;
            this.Operacao = Operacao;
            this.Perfil = Perfil;
            this.Aplicacao = Aplicacao;
            this.Pagina = Pagina;
            this.Descritivo = Descritivo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class wsAuditoriaWebbankResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="wsAuditoriaWebbankResponse", Namespace="http://tempuri.org/", Order=0)]
        public GCC.Permissoes.wsAuditoriaWebbankResponseBody Body;
        
        public wsAuditoriaWebbankResponse() {
        }
        
        public wsAuditoriaWebbankResponse(GCC.Permissoes.wsAuditoriaWebbankResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class wsAuditoriaWebbankResponseBody {
        
        public wsAuditoriaWebbankResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : GCC.Permissoes.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<GCC.Permissoes.Service1Soap>, GCC.Permissoes.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GCC.Permissoes.wsValUsrPerfilResponse GCC.Permissoes.Service1Soap.wsValUsrPerfil(GCC.Permissoes.wsValUsrPerfilRequest request) {
            return base.Channel.wsValUsrPerfil(request);
        }
        
        public bool wsValUsrPerfil(string User_ID, string Rq_Page, string User_Perfil, string App) {
            GCC.Permissoes.wsValUsrPerfilRequest inValue = new GCC.Permissoes.wsValUsrPerfilRequest();
            inValue.Body = new GCC.Permissoes.wsValUsrPerfilRequestBody();
            inValue.Body.User_ID = User_ID;
            inValue.Body.Rq_Page = Rq_Page;
            inValue.Body.User_Perfil = User_Perfil;
            inValue.Body.App = App;
            GCC.Permissoes.wsValUsrPerfilResponse retVal = ((GCC.Permissoes.Service1Soap)(this)).wsValUsrPerfil(inValue);
            return retVal.Body.wsValUsrPerfilResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GCC.Permissoes.wsValUsrPerfilResponse> GCC.Permissoes.Service1Soap.wsValUsrPerfilAsync(GCC.Permissoes.wsValUsrPerfilRequest request) {
            return base.Channel.wsValUsrPerfilAsync(request);
        }
        
        public System.Threading.Tasks.Task<GCC.Permissoes.wsValUsrPerfilResponse> wsValUsrPerfilAsync(string User_ID, string Rq_Page, string User_Perfil, string App) {
            GCC.Permissoes.wsValUsrPerfilRequest inValue = new GCC.Permissoes.wsValUsrPerfilRequest();
            inValue.Body = new GCC.Permissoes.wsValUsrPerfilRequestBody();
            inValue.Body.User_ID = User_ID;
            inValue.Body.Rq_Page = Rq_Page;
            inValue.Body.User_Perfil = User_Perfil;
            inValue.Body.App = App;
            return ((GCC.Permissoes.Service1Soap)(this)).wsValUsrPerfilAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GCC.Permissoes.wsValPerfilFuncaoResponse GCC.Permissoes.Service1Soap.wsValPerfilFuncao(GCC.Permissoes.wsValPerfilFuncaoRequest request) {
            return base.Channel.wsValPerfilFuncao(request);
        }
        
        public bool wsValPerfilFuncao(string wsPerfil, string wsOperacao) {
            GCC.Permissoes.wsValPerfilFuncaoRequest inValue = new GCC.Permissoes.wsValPerfilFuncaoRequest();
            inValue.Body = new GCC.Permissoes.wsValPerfilFuncaoRequestBody();
            inValue.Body.wsPerfil = wsPerfil;
            inValue.Body.wsOperacao = wsOperacao;
            GCC.Permissoes.wsValPerfilFuncaoResponse retVal = ((GCC.Permissoes.Service1Soap)(this)).wsValPerfilFuncao(inValue);
            return retVal.Body.wsValPerfilFuncaoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GCC.Permissoes.wsValPerfilFuncaoResponse> GCC.Permissoes.Service1Soap.wsValPerfilFuncaoAsync(GCC.Permissoes.wsValPerfilFuncaoRequest request) {
            return base.Channel.wsValPerfilFuncaoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GCC.Permissoes.wsValPerfilFuncaoResponse> wsValPerfilFuncaoAsync(string wsPerfil, string wsOperacao) {
            GCC.Permissoes.wsValPerfilFuncaoRequest inValue = new GCC.Permissoes.wsValPerfilFuncaoRequest();
            inValue.Body = new GCC.Permissoes.wsValPerfilFuncaoRequestBody();
            inValue.Body.wsPerfil = wsPerfil;
            inValue.Body.wsOperacao = wsOperacao;
            return ((GCC.Permissoes.Service1Soap)(this)).wsValPerfilFuncaoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GCC.Permissoes.wsValUsrResponse GCC.Permissoes.Service1Soap.wsValUsr(GCC.Permissoes.wsValUsrRequest request) {
            return base.Channel.wsValUsr(request);
        }
        
        public bool wsValUsr(string User_ID, string Operacao) {
            GCC.Permissoes.wsValUsrRequest inValue = new GCC.Permissoes.wsValUsrRequest();
            inValue.Body = new GCC.Permissoes.wsValUsrRequestBody();
            inValue.Body.User_ID = User_ID;
            inValue.Body.Operacao = Operacao;
            GCC.Permissoes.wsValUsrResponse retVal = ((GCC.Permissoes.Service1Soap)(this)).wsValUsr(inValue);
            return retVal.Body.wsValUsrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GCC.Permissoes.wsValUsrResponse> GCC.Permissoes.Service1Soap.wsValUsrAsync(GCC.Permissoes.wsValUsrRequest request) {
            return base.Channel.wsValUsrAsync(request);
        }
        
        public System.Threading.Tasks.Task<GCC.Permissoes.wsValUsrResponse> wsValUsrAsync(string User_ID, string Operacao) {
            GCC.Permissoes.wsValUsrRequest inValue = new GCC.Permissoes.wsValUsrRequest();
            inValue.Body = new GCC.Permissoes.wsValUsrRequestBody();
            inValue.Body.User_ID = User_ID;
            inValue.Body.Operacao = Operacao;
            return ((GCC.Permissoes.Service1Soap)(this)).wsValUsrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GCC.Permissoes.wsAccessControlResponse GCC.Permissoes.Service1Soap.wsAccessControl(GCC.Permissoes.wsAccessControlRequest request) {
            return base.Channel.wsAccessControl(request);
        }
        
        public bool wsAccessControl(string User_ID, string Operacao, string Aplicacao) {
            GCC.Permissoes.wsAccessControlRequest inValue = new GCC.Permissoes.wsAccessControlRequest();
            inValue.Body = new GCC.Permissoes.wsAccessControlRequestBody();
            inValue.Body.User_ID = User_ID;
            inValue.Body.Operacao = Operacao;
            inValue.Body.Aplicacao = Aplicacao;
            GCC.Permissoes.wsAccessControlResponse retVal = ((GCC.Permissoes.Service1Soap)(this)).wsAccessControl(inValue);
            return retVal.Body.wsAccessControlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GCC.Permissoes.wsAccessControlResponse> GCC.Permissoes.Service1Soap.wsAccessControlAsync(GCC.Permissoes.wsAccessControlRequest request) {
            return base.Channel.wsAccessControlAsync(request);
        }
        
        public System.Threading.Tasks.Task<GCC.Permissoes.wsAccessControlResponse> wsAccessControlAsync(string User_ID, string Operacao, string Aplicacao) {
            GCC.Permissoes.wsAccessControlRequest inValue = new GCC.Permissoes.wsAccessControlRequest();
            inValue.Body = new GCC.Permissoes.wsAccessControlRequestBody();
            inValue.Body.User_ID = User_ID;
            inValue.Body.Operacao = Operacao;
            inValue.Body.Aplicacao = Aplicacao;
            return ((GCC.Permissoes.Service1Soap)(this)).wsAccessControlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GCC.Permissoes.wsAuditoriaWebbankResponse GCC.Permissoes.Service1Soap.wsAuditoriaWebbank(GCC.Permissoes.wsAuditoriaWebbankRequest request) {
            return base.Channel.wsAuditoriaWebbank(request);
        }
        
        public void wsAuditoriaWebbank(string User_ID, string Operacao, string Perfil, string Aplicacao, string Pagina, string Descritivo) {
            GCC.Permissoes.wsAuditoriaWebbankRequest inValue = new GCC.Permissoes.wsAuditoriaWebbankRequest();
            inValue.Body = new GCC.Permissoes.wsAuditoriaWebbankRequestBody();
            inValue.Body.User_ID = User_ID;
            inValue.Body.Operacao = Operacao;
            inValue.Body.Perfil = Perfil;
            inValue.Body.Aplicacao = Aplicacao;
            inValue.Body.Pagina = Pagina;
            inValue.Body.Descritivo = Descritivo;
            GCC.Permissoes.wsAuditoriaWebbankResponse retVal = ((GCC.Permissoes.Service1Soap)(this)).wsAuditoriaWebbank(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GCC.Permissoes.wsAuditoriaWebbankResponse> GCC.Permissoes.Service1Soap.wsAuditoriaWebbankAsync(GCC.Permissoes.wsAuditoriaWebbankRequest request) {
            return base.Channel.wsAuditoriaWebbankAsync(request);
        }
        
        public System.Threading.Tasks.Task<GCC.Permissoes.wsAuditoriaWebbankResponse> wsAuditoriaWebbankAsync(string User_ID, string Operacao, string Perfil, string Aplicacao, string Pagina, string Descritivo) {
            GCC.Permissoes.wsAuditoriaWebbankRequest inValue = new GCC.Permissoes.wsAuditoriaWebbankRequest();
            inValue.Body = new GCC.Permissoes.wsAuditoriaWebbankRequestBody();
            inValue.Body.User_ID = User_ID;
            inValue.Body.Operacao = Operacao;
            inValue.Body.Perfil = Perfil;
            inValue.Body.Aplicacao = Aplicacao;
            inValue.Body.Pagina = Pagina;
            inValue.Body.Descritivo = Descritivo;
            return ((GCC.Permissoes.Service1Soap)(this)).wsAuditoriaWebbankAsync(inValue);
        }
    }
}
